# Generated by Django 4.2.13 on 2024-06-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
