# Generated by Django 4.2.13 on 2024-06-11 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0002_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], default='monday', max_length=10)),
                ('time', models.CharField(choices=[('08:00', '8:00 AM - 9:00 AM'), ('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM'), ('14:00', '2:00 PM - 3:00 PM'), ('15:00', '3:00 PM - 4:00 PM'), ('16:00', '4:00 PM - 5:00 PM'), ('17:00', '5:00 PM - 6:00 PM')], default='08:00', max_length=5)),
                ('session_type', models.CharField(choices=[('consultation', 'Consultation'), ('personal_training', 'Personal Training')], default='consultation', max_length=20)),
                ('duration', models.IntegerField(default=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
