# Generated by Django 4.2.13 on 2024-06-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
