# Generated by Django 4.2.13 on 2024-06-11 15:57

import bookings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_contact_email_booking_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=bookings.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='session_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('personal_training', 'Personal Training')], max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('08:00', '8:00 AM - 9:00 AM'), ('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM'), ('14:00', '2:00 PM - 3:00 PM'), ('15:00', '3:00 PM - 4:00 PM'), ('16:00', '4:00 PM - 5:00 PM'), ('17:00', '5:00 PM - 6:00 PM')], max_length=20),
        ),
    ]
