# Generated by Django 4.2.13 on 2024-06-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_date_alter_booking_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('date', 'time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
