# Generated by Django 4.2.13 on 2024-06-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_unique_together_remove_booking_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(default='Any additional information please provide here...', max_length=1000),
        ),
    ]
