# Generated by Django 4.2.13 on 2024-06-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_additional_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='additional_info',
            field=models.TextField(max_length=1000),
        ),
    ]
